/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controleur.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author btssio
 */
public class VueGCR extends VueAbstraite {

    /**
     * Creates new form JFrameCR
     */
    public VueGCR(CtrlAbstrait ctrl) {
        super(ctrl);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCR = new javax.swing.JButton();
        jButtonVisiteurs = new javax.swing.JButton();
        jButtonPraticiens = new javax.swing.JButton();
        jButtonMedicaments = new javax.swing.JButton();
        jButtonQuitter = new javax.swing.JButton();
        jLabelCR = new javax.swing.JLabel();
        jLabelVisiteurs = new javax.swing.JLabel();
        jLabelPraticiens = new javax.swing.JLabel();
        jLabelMedicaments = new javax.swing.JLabel();
        jLabelQuitter = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelGCR = new javax.swing.JLabel();
        jLabelAccueilVisiteur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCRActionPerformed(evt);
            }
        });

        jButtonVisiteurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisiteursActionPerformed(evt);
            }
        });

        jButtonPraticiens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPraticiensActionPerformed(evt);
            }
        });

        jButtonMedicaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMedicamentsActionPerformed(evt);
            }
        });

        jButtonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitterActionPerformed(evt);
            }
        });

        jLabelCR.setText("Comptes - Rendus");

        jLabelVisiteurs.setText("Visiteurs");

        jLabelPraticiens.setText("Praticiens");

        jLabelMedicaments.setText("Médicaments");

        jLabelQuitter.setText("Quitter");

        jPanel1.setBackground(new java.awt.Color(70, 121, 227));
        jPanel1.setForeground(new java.awt.Color(51, 143, 207));

        jLabelGCR.setForeground(new java.awt.Color(253, 239, 239));
        jLabelGCR.setText("GESTION DES COMPTES RENDUS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(jLabelGCR)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelAccueilVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabelGCR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabelAccueilVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelQuitter))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMedicaments, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMedicaments))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCR, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCR))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPraticiens, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPraticiens))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVisiteurs, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelVisiteurs)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCR)
                    .addComponent(jButtonCR, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVisiteurs)
                    .addComponent(jButtonVisiteurs, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPraticiens)
                    .addComponent(jButtonPraticiens, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMedicaments)
                    .addComponent(jButtonMedicaments, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelQuitter)
                    .addComponent(jButtonQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCRActionPerformed
        try {
            ((CtrlGCR)controleur).OuvrirVueCR();
        } catch (Exception ex) {
            Logger.getLogger(VueGCR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCRActionPerformed

    private void jButtonVisiteursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisiteursActionPerformed
        try {
            ((CtrlGCR)controleur).OuvrirVueVisiteur();
        } catch (Exception ex) {
            Logger.getLogger(VueGCR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonVisiteursActionPerformed

    private void jButtonPraticiensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPraticiensActionPerformed
        try {
            ((CtrlGCR)controleur).OuvrirVuePraticien();
        } catch (Exception ex) {
            Logger.getLogger(VueGCR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPraticiensActionPerformed

    private void jButtonMedicamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMedicamentsActionPerformed
        try {
            ((CtrlGCR)controleur).OuvrirVueMedicament();
        } catch (Exception ex) {
            Logger.getLogger(VueGCR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonMedicamentsActionPerformed

    private void jButtonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitterActionPerformed
        try {
            ((CtrlGCR)controleur).Quitter();
        } catch (Exception ex) {
            Logger.getLogger(VueGCR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonQuitterActionPerformed

    public JLabel getjLabelAccueilVisiteur() {
        return jLabelAccueilVisiteur;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCR;
    private javax.swing.JButton jButtonMedicaments;
    private javax.swing.JButton jButtonPraticiens;
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonVisiteurs;
    private javax.swing.JLabel jLabelAccueilVisiteur;
    private javax.swing.JLabel jLabelCR;
    private javax.swing.JLabel jLabelGCR;
    private javax.swing.JLabel jLabelMedicaments;
    private javax.swing.JLabel jLabelPraticiens;
    private javax.swing.JLabel jLabelQuitter;
    private javax.swing.JLabel jLabelVisiteurs;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
