/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import com.toedter.calendar.JDateChooser;
import controleur.CtrlAbstrait;
import controleur.CtrlNouveauVisiteur;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author btssio
 */
public class VueNouveauVisiteur extends VueAbstraite {
    
    
    DefaultComboBoxModel modelJComboBoxLabo;
    DefaultComboBoxModel modelJComboBoxSecteur;

    /**
     * Creates new form VueNouveauVisiteur
     */
    public VueNouveauVisiteur(CtrlAbstrait ctrl) {
        super(ctrl);
        initComponents();
        modelJComboBoxLabo = new DefaultComboBoxModel();
        modelJComboBoxSecteur = new DefaultComboBoxModel();
        jComboBoxLabo.setModel(modelJComboBoxLabo);
        jComboBoxSecteur.setModel(modelJComboBoxSecteur);
    }

    public JButton getjButtonQuitter() {
        return jButtonQuitter;
    }

    public void setjButtonQuitter(JButton jButtonQuitter) {
        this.jButtonQuitter = jButtonQuitter;
    }

    public JButton getjButtonValider() {
        return jButtonValider;
    }

    public void setjButtonValider(JButton jButtonValider) {
        this.jButtonValider = jButtonValider;
    }

    public JComboBox getjComboBoxLabo() {
        return jComboBoxLabo;
    }

    public void setjComboBoxLabo(JComboBox jComboBoxLabo) {
        this.jComboBoxLabo = jComboBoxLabo;
    }

    public JComboBox getjComboBoxSecteur() {
        return jComboBoxSecteur;
    }

    public void setjComboBoxSecteur(JComboBox jComboBoxSecteur) {
        this.jComboBoxSecteur = jComboBoxSecteur;
    }

    public JTextField getjTextFieldAdresse() {
        return jTextFieldAdresse;
    }

    public void setjTextFieldAdresse(JTextField jTextFieldAdresse) {
        this.jTextFieldAdresse = jTextFieldAdresse;
    }

    public JTextField getjTextFieldCP() {
        return jTextFieldCP;
    }

    public void setjTextFieldCP(JTextField jTextFieldCP) {
        this.jTextFieldCP = jTextFieldCP;
    }

    public JTextField getjTextFieldMatricule() {
        return jTextFieldMatricule;
    }

    public void setjTextFieldMatricule(JTextField jTextFieldMatricule) {
        this.jTextFieldMatricule = jTextFieldMatricule;
    }

    public JTextField getjTextFieldNom() {
        return jTextFieldNom;
    }

    public void setjTextFieldNom(JTextField jTextFieldNom) {
        this.jTextFieldNom = jTextFieldNom;
    }

    public JTextField getjTextFieldPrenom() {
        return jTextFieldPrenom;
    }

    public void setjTextFieldPrenom(JTextField jTextFieldPrenom) {
        this.jTextFieldPrenom = jTextFieldPrenom;
    }

    public JTextField getjTextFieldVille() {
        return jTextFieldVille;
    }

    public void setjTextFieldVille(JTextField jTextFieldVille) {
        this.jTextFieldVille = jTextFieldVille;
    }

    public DefaultComboBoxModel getModelJComboBoxLabo() {
        return modelJComboBoxLabo;
    }

    public void setModelJComboBoxLabo(DefaultComboBoxModel modelJComboBoxLabo) {
        this.modelJComboBoxLabo = modelJComboBoxLabo;
    }

    public DefaultComboBoxModel getModelJComboBoxSecteur() {
        return modelJComboBoxSecteur;
    }

    public void setModelJComboBoxSecteur(DefaultComboBoxModel modelJComboBoxSecteur) {
        this.modelJComboBoxSecteur = modelJComboBoxSecteur;
    }

    public JDateChooser getjDateChooserEmbauche() {
        return jDateChooserEmbauche;
    }

    public void setjDateChooserEmbauche(JDateChooser jDateChooserEmbauche) {
        this.jDateChooserEmbauche = jDateChooserEmbauche;
    }

    public JLabel getjLabelResultat() {
        return jLabelResultat;
    }

    public void setjLabelResultat(JLabel jLabelResultat) {
        this.jLabelResultat = jLabelResultat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNouveauVisiteur = new javax.swing.JLabel();
        jLabelMatricule = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelAdresse = new javax.swing.JLabel();
        jLabelVille = new javax.swing.JLabel();
        jLabelSecteur = new javax.swing.JLabel();
        jLabelLabo = new javax.swing.JLabel();
        jButtonValider = new javax.swing.JButton();
        jButtonQuitter = new javax.swing.JButton();
        jTextFieldMatricule = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldPrenom = new javax.swing.JTextField();
        jTextFieldAdresse = new javax.swing.JTextField();
        jTextFieldCP = new javax.swing.JTextField();
        jTextFieldVille = new javax.swing.JTextField();
        jComboBoxSecteur = new javax.swing.JComboBox();
        jComboBoxLabo = new javax.swing.JComboBox();
        jDateChooserEmbauche = new com.toedter.calendar.JDateChooser();
        jLabelEmbauche = new javax.swing.JLabel();
        jLabelResultat = new javax.swing.JLabel();

        jLabelNouveauVisiteur.setText("NOUVEAU VISITEUR");

        jLabelMatricule.setText("Matricule :");

        jLabelNom.setText("Nom :");

        jLabelPrenom.setText("Prenom :");

        jLabelAdresse.setText("Adresse :");

        jLabelVille.setText("Ville :");

        jLabelSecteur.setText("Secteur :");

        jLabelLabo.setText("Labo :");

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });

        jButtonQuitter.setText("Quitter");

        jComboBoxSecteur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxLabo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelEmbauche.setText("Date d'embauche :");

        jLabelResultat.setForeground(new java.awt.Color(240, 15, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelNouveauVisiteur))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonQuitter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonValider))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelAdresse, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelVille, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelSecteur, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelLabo, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(jLabelNom, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPrenom, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelEmbauche, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelMatricule, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxSecteur, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxLabo, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jDateChooserEmbauche, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(0, 104, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNouveauVisiteur)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMatricule)
                            .addComponent(jTextFieldMatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNom))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrenom))
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooserEmbauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelEmbauche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdresse)
                    .addComponent(jTextFieldAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVille, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSecteur)
                    .addComponent(jComboBoxSecteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLabo)
                    .addComponent(jComboBoxLabo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabelResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValider)
                    .addComponent(jButtonQuitter))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        try {
            ((CtrlNouveauVisiteur)controleur).insererNouveauVisiteur();
        } catch (Exception ex) {
            Logger.getLogger(VueNouveauVisiteur.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonValiderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonQuitter;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JComboBox jComboBoxLabo;
    private javax.swing.JComboBox jComboBoxSecteur;
    private com.toedter.calendar.JDateChooser jDateChooserEmbauche;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelEmbauche;
    private javax.swing.JLabel jLabelLabo;
    private javax.swing.JLabel jLabelMatricule;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNouveauVisiteur;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelResultat;
    private javax.swing.JLabel jLabelSecteur;
    private javax.swing.JLabel jLabelVille;
    private javax.swing.JTextField jTextFieldAdresse;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldMatricule;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldPrenom;
    private javax.swing.JTextField jTextFieldVille;
    // End of variables declaration//GEN-END:variables
}
